VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "IMDIDocument"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Function CommandHandler(tool As ActiveBar2LibraryCtl.tool) As Boolean
End Function

Public Function InitDoc(ab As ActiveBar2LibraryCtl.ActiveBar2, sFile As String, bNew As Boolean) As Boolean
End Function
